#! /bin/sh
#######################################################################################
#
#  application name: dnsactual
#  other files: dnsactual.conf (keeps the last updated ip)
#               dnsactual.log  (register date & time of the actualization)
#		(files created on first run, if missing except domains.txt)
#		domains.txt (list of site hashes from freedns.afraid.org)
#	(format:  http://freedns.afraid.org/dynamic/update.php?[site-hash-code-here])
#  other programs needed:
#		lynx - text web browser
#  optional programs:
#		twidge - CLI twitter updater
#  Author: Ernest Danton
#  Date: 01/29/2007
#
#  Updated by: Zach Falle
#
#######################################################################################

if test -f dnsactual.conf
	then
		CacheIP=`cat dnsactual.conf`
		
fi
CurrIP=$(lynx -dump "http://checkip.dyndns.org" | cut -d " " -f 7)
#echo "compair $CurrIP to $CacheIP"
if [ "$CurrIP" = "$CacheIP" ]
	then
#	Both IPs are equal
		sleep 1
		twidge update "$CurrIP `date`"
		#echo "$CurrIP `date`"
	else
#	The IP has changed
		sleep 1
		twidge update "$CurrIP `date` IP has changed @unl33t"
		#echo "$CurrIP `date` IP has changed @unl33t"
		for i in `cat domains.txt`
			do
				wget "$i" -o /dev/null -O /dev/stdout
				#echo "Updating would be happeneing here"
		done
		echo "$CurrIP	`date`" >> dnsactual.log
fi
rm -f dnsactual.conf
echo $CurrIP > dnsactual.conf
