#! /bin/bash
#######################################################################################
#
#  application name: dnsactual
#  other files: dnsactual.conf (keeps the last updated ip)
#               dnsactual.log  (register date & time of the actualization)
#		(files created on first run, if missing except domains.txt)
#		domains.txt (list of site hashes from freedns.afraid.org)
#	(format:  http://freedns.afraid.org/dynamic/update.php?[site-hash-code-here])
#  other programs needed:
#		lynx - text web browser
#  optional programs:
#		t (ruby gem)
#  Author: Ernest Danton
#  Date: 01/29/2007
#
#  Updated by: Zach Falle
#
#######################################################################################

if test -f dnsactual.conf
	then
		CacheIP=`cat dnsactual.last`
	else
		CacheIP=""
fi


CurrIP=$(lynx -dump "http://checkip.dyndns.org" | cut -d " " -f 7)
#echo "compare $CurrIP to $CacheIP"

if [ "$CurrIP" == "$CacheIP" ]
	then
#	Both IPs are equal
		/usr/local/bin/t update "$CurrIP `date`"
		#echo "$CurrIP `date`"
	else
#	The IP has changed
		/usr/local/bin/t update "$CurrIP `date` IP has changed @unl33t"
		#echo "$CurrIP `date` IP has changed @unl33t"
		for i in `cut -d "|" -f 3 domains`
			do
				wget "$i" -o /dev/null -O /dev/stdout
				#echo "Updating would be happeneing here"
		done
		echo "$CurrIP	`date`" >> dnsactual.log
fi
echo $CurrIP > dnsactual.last
sleep 1
